import { createMultiplayerHostController } from "nexus-kits-host";
import { createPeerJSTransportProvider } from "nexus-kits-peerjs";
import { applyKnockoutInputs, createInitialKnockoutState, createKnockoutSimulationAdapter, stepKnockoutState } from "./simulation.mjs";

const $ = (value) => document.querySelector(value), canvas = $("#game"), ctx = canvas.getContext("2d");
const ui = { start: $("#start"), lobby: $("#lobby"), actions: $("#menuActions"), hud: $("#hud"), status: $("#statusText"), dot: $("#statusDot"), net: $("#netState"), result: $("#result") };
let mode = "menu", session = null, campaign = null, campaignRival = 0, input = { left: false, right: false, punch: false }, last = performance.now(), display = [{ x: 300 }, { x: 660 }], roomCode = "";
const randomCode = () => Array.from({ length: 6 }, () => "ABCDEFGHJKLMNPQRSTUVWXYZ23456789"[Math.floor(Math.random() * 32)]).join("");
const currentInput = () => ({ move: (input.right ? 1 : 0) - (input.left ? 1 : 0), punch: input.punch });

function setStatus(phase, detail) { const labels = { idle: "Online lobby", creating: "Creating", waiting: "Waiting", connecting: "Connecting", syncing: "Syncing", ready: "Ready", "connection-lost": "Connection lost", failed: "Connection failed", closed: "Closed", menu: "Attract mode" }; ui.status.textContent = labels[phase] ?? phase; ui.dot.classList.toggle("ready", phase === "ready"); if (detail) ui.net.textContent = detail; }
function showResult(title, copy) { $("#resultTitle").textContent = title; $("#resultCopy").textContent = copy; ui.result.hidden = false; }
function provider() { if (typeof window.Peer !== "function") throw new Error("PeerJS did not load."); return createPeerJSTransportProvider({ Peer: window.Peer, connectionTimeoutMs: 12000, peerOptions: { config: { iceServers: [{ urls: "stun:stun.l.google.com:19302" }] } } }); }
function createSession(role) { const next = createMultiplayerHostController({ provider: provider(), simulation: createKnockoutSimulationAdapter({ authoritative: role === "host" }), tickRate: 60, snapshotRate: 20 }); next.onStatus((status) => { setStatus(status.phase, status.phase === "ready" ? `Synchronized · ${status.latencyMs} ms` : undefined); if (status.phase === "ready") { mode = "multi"; ui.start.hidden = true; ui.hud.hidden = false; } if (["connection-lost", "failed"].includes(status.phase)) showResult("Connection lost", "The peer connection closed. Create a new room to play again."); }); return next; }
async function host() { try { session?.dispose(); session = createSession("host"); roomCode = randomCode(); $("#roomCode").textContent = roomCode; setStatus("creating", "Opening signaling…"); await session.createSession({ peerId: `nexus-knockout-${roomCode.toLowerCase()}` }); setStatus("waiting", "Room open. Share the code and keep this tab active."); } catch (error) { setStatus("failed", error.message); } }
async function join() { const value = $("#joinCode").value.trim().toLowerCase(); if (!/^[a-z2-9]{6}$/.test(value)) return setStatus("failed", "Enter a valid six-character room code."); try { session?.dispose(); session = createSession("client"); setStatus("connecting", "Finding the host…"); await session.joinSession({ sessionId: `nexus-knockout-${value}` }); setStatus("syncing", "Transport open. Synchronizing ticks…"); } catch (error) { setStatus("failed", error.message); } }
function circuit() { session?.dispose(); session = null; campaignRival = 0; campaign = createInitialKnockoutState({ authoritative: true }); mode = "campaign"; ui.start.hidden = true; ui.hud.hidden = false; setStatus("ready"); }
function showMenu() { session?.dispose(); session = null; campaign = null; mode = "menu"; ui.start.hidden = false; ui.lobby.hidden = true; ui.actions.hidden = false; ui.hud.hidden = true; ui.result.hidden = true; setStatus("menu"); }

function renderState() { if (mode !== "multi" || !session) return campaign ?? createInitialKnockoutState(); const frame = session.getRenderState(), state = frame.state; if (session.getStatus().role === "client" && frame.interpolation.length > 1) { const target = state.tick - 6, samples = frame.interpolation; let left = samples[0], right = samples.at(-1); for (let i = 1; i < samples.length; i += 1) if (samples[i].tick >= target) { left = samples[i - 1]; right = samples[i]; break; } const alpha = Math.max(0, Math.min(1, (target - left.tick) / Math.max(1, right.tick - left.tick))); state.fighters[0].x = left.state.fighters[0].x + (right.state.fighters[0].x - left.state.fighters[0].x) * alpha; } return state; }
function update(delta) { if (mode === "multi" && session) { session.setLocalInput(currentInput()); session.tick(delta); const state = session.getRenderState().state; if (state.phase === "ended" && ui.result.hidden) { const own = session.getStatus().role === "host" ? 0 : 1; showResult(state.winner === own ? "Circuit won" : "Circuit lost", "Host-confirmed best-of-three result."); } } else if (mode === "campaign") { const rival = campaign.fighters[1], you = campaign.fighters[0], distance = rival.x - you.x, cadence = Math.max(22, 43 - campaignRival * 4); const ai = { move: distance > 125 ? -1 : distance < 95 ? 1 : 0, punch: distance < 140 && campaign.tick % cadence === 0 }; campaign = stepKnockoutState(applyKnockoutInputs(campaign, { host: currentInput(), local: ai })); if (campaign.phase === "ended" && ui.result.hidden) { if (campaign.winner === 0 && campaignRival < 4) { campaignRival += 1; campaign = createInitialKnockoutState({ authoritative: true }); setStatus("ready"); } else showResult(campaign.winner === 0 ? "Circuit champion" : "Circuit lost", campaign.winner === 0 ? "Five deterministic rivals defeated." : `Rival ${campaignRival + 1} ended the run.`); } } }

function arena() { const gradient = ctx.createLinearGradient(0, 0, 0, 540); gradient.addColorStop(0, "#071009"); gradient.addColorStop(1, "#101b0d"); ctx.fillStyle = gradient; ctx.fillRect(0, 0, 960, 540); ctx.globalAlpha = .13; ctx.strokeStyle = "#baff51"; for (let x = -200; x < 1160; x += 65) { ctx.beginPath(); ctx.moveTo(480, 170); ctx.lineTo(x, 540); ctx.stroke(); } ctx.globalAlpha = 1; ctx.fillStyle = "#071008"; ctx.beginPath(); ctx.roundRect(55, 420, 850, 70, 22); ctx.fill(); ctx.strokeStyle = "#d0a327"; ctx.lineWidth = 5; ctx.stroke(); }
function robot(fighter, index, time) { const x = display[index].x += (fighter.x - display[index].x) * .24, face = index ? -1 : 1, punch = fighter.punchTicks > 0 ? Math.sin((12 - fighter.punchTicks) / 12 * Math.PI) : 0, color = index ? "#ed4827" : "#e9b41e", trim = index ? "#ffc33c" : "#fff08a"; ctx.save(); ctx.translate(x, 395 + Math.sin(time * 4 + index) * 2); ctx.fillStyle = "#0006"; ctx.beginPath(); ctx.ellipse(0, 68, 66, 12, 0, 0, Math.PI * 2); ctx.fill(); ctx.fillStyle = color; ctx.beginPath(); ctx.roundRect(-38, -48, 76, 85, 18); ctx.fill(); ctx.strokeStyle = trim; ctx.lineWidth = 5; ctx.stroke(); ctx.fillStyle = "#111a12"; ctx.beginPath(); ctx.roundRect(-28, -38, 56, 26, 9); ctx.fill(); ctx.fillStyle = "#fff7a0"; ctx.beginPath(); ctx.arc(face * 15, -25, 5, 0, Math.PI * 2); ctx.fill(); const hand = face * (82 + punch * 56); ctx.strokeStyle = "#263027"; ctx.lineWidth = 17; ctx.beginPath(); ctx.moveTo(face * 36, 0); ctx.lineTo(hand - face * 15, -2); ctx.stroke(); ctx.fillStyle = color; ctx.beginPath(); ctx.arc(hand, -2, 20, 0, Math.PI * 2); ctx.fill(); ctx.strokeStyle = trim; ctx.lineWidth = 4; ctx.stroke(); ctx.restore(); }
function draw(now) { const state = renderState(); arena(); state.fighters.forEach((fighter, index) => robot(fighter, index, now / 1000)); if (!ui.hud.hidden) { $("#p1Hp").textContent = state.fighters[0].hp; $("#p2Hp").textContent = state.fighters[1].hp; $("#p1Fill").style.width = `${state.fighters[0].hp}%`; $("#p2Fill").style.width = `${state.fighters[1].hp}%`; $("#roundLabel").textContent = mode === "campaign" ? `${campaignRival + 1}/5` : state.round; $("#phaseLabel").textContent = mode === "campaign" ? "Rival" : state.phase; $("#p1Name").textContent = mode === "multi" ? "Gold · Host" : "Gold · You"; $("#p2Name").textContent = mode === "multi" ? "Orange · Guest" : `Orange · Rival ${campaignRival + 1}`; } }
function loop(now) { const delta = Math.min(.1, (now - last) / 1000); last = now; update(delta); draw(now); requestAnimationFrame(loop); }

addEventListener("keydown", (event) => { if (["KeyA", "ArrowLeft"].includes(event.code)) input.left = true; if (["KeyD", "ArrowRight"].includes(event.code)) input.right = true; if (["Space", "KeyJ"].includes(event.code)) input.punch = true; }); addEventListener("keyup", (event) => { if (["KeyA", "ArrowLeft"].includes(event.code)) input.left = false; if (["KeyD", "ArrowRight"].includes(event.code)) input.right = false; if (["Space", "KeyJ"].includes(event.code)) input.punch = false; });
document.querySelectorAll("[data-control]").forEach((button) => { const name = button.dataset.control; button.addEventListener("pointerdown", (event) => { event.preventDefault(); button.classList.add("active"); input[name] = true; }); for (const type of ["pointerup", "pointercancel", "pointerleave"]) button.addEventListener(type, () => { button.classList.remove("active"); input[name] = false; }); });
$("#circuitBtn").onclick = circuit; $("#onlineBtn").onclick = () => { ui.actions.hidden = true; ui.lobby.hidden = false; setStatus("idle", "Choose Create or Join."); }; $("#hostBtn").onclick = host; $("#joinBtn").onclick = join; $("#copyBtn").onclick = async () => { if (roomCode) { await navigator.clipboard?.writeText(roomCode); ui.net.textContent = "Room code copied."; } }; $("#backBtn").onclick = showMenu; $("#resultBtn").onclick = showMenu;
$("#hostTab").onclick = () => { $("#hostPane").hidden = false; $("#joinPane").hidden = true; $("#hostTab").classList.add("selected"); $("#joinTab").classList.remove("selected"); $("#youRole").textContent = "You · Gold robot"; }; $("#joinTab").onclick = () => { $("#hostPane").hidden = true; $("#joinPane").hidden = false; $("#joinTab").classList.add("selected"); $("#hostTab").classList.remove("selected"); $("#youRole").textContent = "You · Orange robot"; };
window.KnockoutCircuit = { version: "0.2.0", createKnockoutSimulationAdapter }; requestAnimationFrame(loop);
